### ISSUE TITLE
安装教程

### ISSUE THREAD

**Issue by CPhyTea** [alexanderkin/ASUS-FL8000UQ-Hackintosh#1]
大佬，有没有最新版本的安装教程呢？
是直接在官网下载beta版本的镜像然后efi替换一下就行了么？

另外，大佬牛逼

**Comment by alexanderkin** [comment]
可以安装描述文件直接OTA升级的，替换EFI就行，注意进系统的时候选preboot就行了，安装完成后进系统安装IntelPowerGadget就可以吧preboot变回你的系统盘名称了。安装过程中如果遇到内核崩溃，清理一次NVRAM就行，建议在安装之前就清理。

**Comment by CPhyTea** [comment]
谢谢老哥
笔芯
