### ISSUE TITLE
有用FL8000UF8550的吗

### ISSUE THREAD

**Issue by lnatpunblhna** [alexanderkin/ASUS-FL8000UQ-Hackintosh#10]
https://user-images.githubusercontent.com/33893697/111272751-faab0000-866d-11eb-9450-049e146e6afd.mp4

第一次安装后，进入二次安装会重启，开了哆嗦模式也是直接就重启了

**Comment by alexanderkin** [comment]
尝试清除NVRAM，建议安装Catalina，BigSur安装经常会失败

**Comment by lnatpunblhna** [comment]
> 尝试清除NVRAM，建议安装Catalina，BigSur安装经常会失败

清除过的 会不会是设备间有什么差异

**Comment by alexanderkin** [comment]
有可能，尝试比较旧一点的EFI

**Comment by lnatpunblhna** [comment]
确实Catalina安装成功
