### ISSUE TITLE
声卡有时候驱动不上

### ISSUE THREAD

**Issue by JSPRKWAN** [alexanderkin/ASUS-FL8000UQ-Hackintosh#11]
网卡已换成BCM943602CS，可以正常使用。声卡有时候驱动不上
<img width="674" alt="截屏2021-08-30 14 05 14" src="https://user-images.githubusercontent.com/71814334/131293139-8f383a40-ce6c-401c-92dc-b352b8d2f255.png">

**Comment by alexanderkin** [comment]
可能和windows声卡驱动有关，从windows重启到mac是没有声音的，只有直接开机进入mac才会有声音
