### ISSUE TITLE
mac OS 13 适配

### ISSUE THREAD

**Issue by Yu-Core** [alexanderkin/ASUS-FL8000UQ-Hackintosh#14]
适配mac OS 13 ，提了一个pr，大佬你审查一下，给点建议。在我的电脑上是可以运行的。
OpenCore更新到了0.8.8，我额外添加了一个USB共享网络的驱动HoRNDIS.kext
![IMG_20230215_170513](https://user-images.githubusercontent.com/96511239/219013926-0c1be9c0-a9ad-41a1-b4bf-5c831e1b7938.jpg)

**Comment by alexanderkin** [comment]
挺好的，我这台电脑已经不用了，后续也不会更新了，如果你愿意的话可以去黑果小兵那边提交pr把我的地址换成你的

**Comment by Yu-Core** [comment]
那太可惜了。我现在对黑苹果还不太熟悉，以后会考虑的。

**Comment by OutlierStar** [comment]
> 适配mac OS 13 ，提了一个pr，大佬你审查一下，给点建议。在我的电脑上是可以运行的。 OpenCore更新到了0.8.8，我额外添加了一个USB共享网络的驱动HoRNDIS.kext ![IMG_20230215_170513](https://user-images.githubusercontent.com/96511239/219013926-0c1be9c0-a9ad-41a1-b4bf-5c831e1b7938.jpg)

可以出个Mac OS 13的教程吗
