### ISSUE TITLE
DW1820A-08PKF4网卡驱动问题

### ISSUE THREAD

**Issue by tarontop** [alexanderkin/ASUS-FL8000UQ-Hackintosh#2]
我将自带网卡换成了DW1820A-08PKF4，发现不但去驱动不了，而且如果不在bios里面把网卡禁掉系统会非常卡，其他都正常，请问这个网卡怎么驱动，如果我在bios里启用Wi-Fi网卡系统会非常卡，导致无法操作。

**Comment by alexanderkin** [comment]
可以参照黑果小兵的教程去驱动 https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html
在使用Airportbrcmfixup的时候将驱动包里的AirportBrcm4360去掉即可

**Comment by tarontop** [comment]
> 可以参照黑果小兵的教程去驱动 https://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html
> 在使用Airportbrcmfixup的时候将驱动包里的AirportBrcm4360去掉即可

问题解决了，需要屏蔽网卡的针脚，目前已经完美驱动
