### ISSUE TITLE
Nvram重置，如何选择u盘启动项？

### ISSUE THREAD

**Issue by CPhyTea** [alexanderkin/ASUS-FL8000UQ-Hackintosh#3]
老哥，进入macos installer，会自动重启。重置nvram，就会找不到u盘的uefi，该如何解决，直接替换硬盘里的efi么？

**Comment by alexanderkin** [comment]
建议将引导放入硬盘，丢失引导的话多重启几次或者拔插几次U盘试试

**Comment by CPhyTea** [comment]
感谢，我中午试试看
