### ISSUE TITLE
Fl8000UN显示有色带问题

### ISSUE THREAD

**Issue by falafalafala1668** [alexanderkin/ASUS-FL8000UQ-Hackintosh#5]
机型：Fl8000UN
系统：10.15.6及11.0b8
EFI无任何修改，与系统无关。曾尝试仿冒0x19160000后色带问题解决，但是性能差劲
手机拍摄（有色带）：
![image](https://user-images.githubusercontent.com/57652508/94278041-f2a2bb00-ff7c-11ea-96d5-5a3c01a3f3f6.jpeg)
电脑截图（无色带）：
![image](https://user-images.githubusercontent.com/57652508/94278329-42818200-ff7d-11ea-9c26-7959a4e922ca.png)
感谢

**Comment by alexanderkin** [comment]
尝试使用59160000替换591B0000，如果不闪屏的话

**Comment by falafalafala1668** [comment]
已改，仍有色带

**Comment by alexanderkin** [comment]
那就不知到是·什么原因了
