### ISSUE TITLE
wifi和蓝牙的驱动怎么弄的。

### ISSUE THREAD

**Issue by WilliamsLee** [alexanderkin/ASUS-FL8000UQ-Hackintosh#8]
麻烦解答一下。说明没太懂。。

**Comment by alexanderkin** [comment]
不知道你说的网卡是什么，如果是intel网卡可以参照这个教程：[Big Sur安装教程 Part 2](https://mp.weixin.qq.com/s?src=11&timestamp=1608085025&ver=2769&signature=ko09u4G1foI5Clc9wXScDaFDUUgPgk8Y1tEBdGCSk837LZy0ZMxLHk61hokKzIKEz*gpjSzEZhrrHIkY1wwAUP39*BDFpXrrZtUWbH5TwC*fbA5YlgejBYj-uPjckRBS&new=1)
DW1820A可以参照这个教程：[DW1820A/BCM94350ZAE/BCM94356ZEPA50DX插入的正确姿势](http://blog.daliansky.net/DW1820A_BCM94350ZAE-driver-inserts-the-correct-posture.html)
AR9565可以参照这个教程：[MAC11.0 BigSur修复AR9565Wi-Fi网卡驱动](https://www.longzc.cn/index.php/archives/306) 
 [AR9565 MAC黑苹果Bluetooth蓝牙驱动教程](https://www.longzc.cn/index.php/archives/308)
