### ISSUE TITLE
声卡驱动

### ISSUE THREAD

**Issue by ultraman-king** [alexanderkin/ASUS-FL8000UQ-Hackintosh#9]
老哥你有没有遇到过有的时候开机声卡无法驱动的问题啊，ntfs的硬盘也识别不出来，偶尔开机很慢。有的时候好有的时候不好。用的你这套efi

**Comment by alexanderkin** [comment]
开机无法驱动声卡我只在windows重启到Mac的时候遇到过，这个好像是把windows的声卡驱动卸载掉就行，其他情况下开机声卡都是正常的。NTFS不读盘已经修复了应该没啥问题，不行就清理一下NVRAM。
